-- needed bootstrap packages
import qualified System.Directory as INIT
import qualified Data.List as INIT
import qualified System.FilePath as INIT

-- command to source a GHCi file
:def source readFile
-- dommand to source a number of GHCi files from the supplied directory
:def sourceDir \dir -> return . concat =<< mapM readFile . map (INIT.combine dir) . filter (".ghci.hs" `INIT.isSuffixOf`) =<< INIT.getDirectoryContents dir

-- source config directory
:cmd INIT.getHomeDirectory >>= \home -> return $ ":sourceDir " ++ INIT.combine (INIT.combine home ".ghc") "ghci.d"
